version: '3'

services:
    php:
        build: .
        working_dir: /var/www/html
        ports:
            - 8000:8000
        volumes:
            - ./:/var/www/html
        command: sh -c "composer install && php artisan serve --host 0.0.0.0 --port=8000"
